_wandb:
    value:
        cli_version: 0.23.0
        e:
            rfkrfir7f8p3bhhul3rlr0v93ddwzlyj:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "467656015872"
                        used: "366532009984"
                email: 17701248665@189.cn
                executable: /data/liuxinyu/miniconda3/envs/GRPO-zero/bin/python
                git:
                    commit: 92052d1b69717be13aee8c452c26ddf68ad4fee9
                    remote: git@github.com:WilmaLiu2005/mathgrpo.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-528afedf-02cf-7380-e22b-e2c05c1be4ec
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-5c46d5eb-0996-a5ac-cb7a-29f274d046a4
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-f57f6d1b-ea13-1480-6321-7a26181b838d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-75acc759-bb26-da0b-21c5-a31dca12e93f
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-7e4da326-2d9e-3530-9f46-673474746e0b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-76f183b8-b750-73bc-b438-404a16ae7b78
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-34823444-9a29-0776-f483-c802c6057039
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-a474810c-7356-b242-d0d8-5e83714655de
                host: nm07-a100-node001
                memory:
                    total: "1082002214912"
                os: Linux-5.15.0-133-generic-x86_64-with-glibc2.35
                program: /home/student008/GRPO-zero/train.py
                python: CPython 3.11.14
                root: /home/student008/GRPO-zero
                startedAt: "2025-11-21T12:31:11.935408Z"
                writerId: rfkrfir7f8p3bhhul3rlr0v93ddwzlyj
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
data:
    value:
        config_name: main
        path: gsm8k
        test_size: 128
model:
    value:
        device: cuda
        dtype: bfloat16
        pretrained_model_path: Qwen2.5-3B-Instruct
training:
    value:
        batch_size: 256
        betas:
            - 0.9
            - 0.999
        ckpt_dir: ckpt
        ckpt_save_interval: 100
        eval_interval: 10
        learning_rate: 1e-05
        log_dir: logs
        max_gen_len: 1024
        max_grad_norm: 1
        max_prompt_len: 512
        memory_efficient_adamw: false
        micro_batch_size: 2
        num_questions_per_batch: 32
        random_seed: 1337
        skip_unfinished_episodes: false
        weight_decay: 0
wandb:
    value:
        artifact_name_prefix: grpo-qwen
        enable: true
        entity: amdyes
        log_text_every: 100
        mode: online
        num_text_samples: 4
        project: mathgrpo
        run_name: ""
        save_ckpt_artifact: false
        watch_log_freq: 100
        watch_model: false
